<template><div><h1 id="正则表达式" tabindex="-1"><a class="header-anchor" href="#正则表达式" aria-hidden="true">#</a> 正则表达式</h1>
<h2 id="创建正则表达式的方式" tabindex="-1"><a class="header-anchor" href="#创建正则表达式的方式" aria-hidden="true">#</a> 创建正则表达式的方式</h2>
<p>创建正则表达式一般有两种方式</p>
<ol>
<li>字面量  <code v-pre>/js/</code></li>
<li>构造函数  <code v-pre>new RegExp()</code></li>
</ol>
<h2 id="匹配字符串" tabindex="-1"><a class="header-anchor" href="#匹配字符串" aria-hidden="true">#</a> 匹配字符串</h2>
<h3 id="test" tabindex="-1"><a class="header-anchor" href="#test" aria-hidden="true">#</a> test</h3>
<p>使用test()可以返回一个布尔值。</p>
<p>示例：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>    <span class="token keyword">var</span> str <span class="token operator">=</span> <span class="token string">'I love js'</span><span class="token punctuation">;</span>
    <span class="token keyword">var</span> pattern <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">js</span><span class="token regex-delimiter">/</span></span><span class="token punctuation">;</span>
    <span class="token comment">//test</span>
    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>pattern<span class="token punctuation">.</span><span class="token function">test</span><span class="token punctuation">(</span>str<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span><span class="token comment">//true</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="exec" tabindex="-1"><a class="header-anchor" href="#exec" aria-hidden="true">#</a> exec</h3>
<p>使用exec()返回匹配到的数据</p>
<p>示例：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>    <span class="token keyword">var</span> str <span class="token operator">=</span> <span class="token string">'I love js'</span><span class="token punctuation">;</span>
    <span class="token keyword">var</span> pattern <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">js</span><span class="token regex-delimiter">/</span></span><span class="token punctuation">;</span>
    <span class="token comment">//exec</span>
    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>pattern<span class="token punctuation">.</span><span class="token function">exec</span><span class="token punctuation">(</span>str<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token comment">//["js", index: 7, input: "I love js", groups: undefined]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="模式修饰符" tabindex="-1"><a class="header-anchor" href="#模式修饰符" aria-hidden="true">#</a> 模式修饰符</h3>
<p>i 不区分大小写
g 全局搜索
m 多行搜索</p>
<h2 id="转义字符" tabindex="-1"><a class="header-anchor" href="#转义字符" aria-hidden="true">#</a> 转义字符</h2>
<p>如果我们需要匹配特殊字符， 就需要转义 。 用<code v-pre>\</code>进行转义</p>
<p>如：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code> <span class="token keyword">var</span> str <span class="token operator">=</span> <span class="token string">'//我是注释'</span>
    <span class="token keyword">var</span> pattern <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">\/</span><span class="token regex-delimiter">/</span></span>
    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>pattern<span class="token punctuation">.</span><span class="token function">exec</span><span class="token punctuation">(</span>str<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token comment">//["/", index: 0, input: "//我是注释", groups: undefined]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>还有其它几种特殊字符：</p>
<p>如<code v-pre>\n</code>, 匹配换行符 也可以使用<code v-pre>\xOA</code>
<code v-pre>\t</code>， 匹配制表符 也可以用<code v-pre>\u0009</code></p>
<h2 id="字符类" tabindex="-1"><a class="header-anchor" href="#字符类" aria-hidden="true">#</a> 字符类</h2>
<p>我们通过<code v-pre>[]</code>来写字符类</p>
<p>示例：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>    <span class="token keyword">var</span> str <span class="token operator">=</span> <span class="token string">'javascript'</span>
    <span class="token keyword">var</span> pattern <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">[sjwelsls]</span><span class="token regex-delimiter">/</span></span>
    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>pattern<span class="token punctuation">.</span><span class="token function">exec</span><span class="token punctuation">(</span>str<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token comment">//["j", index: 0, input: "javascript", groups: undefined]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>使用字符类我们只需要匹配到其中一个字符。返回的是匹配到的第一个字符。</p>
<h3 id="取反" tabindex="-1"><a class="header-anchor" href="#取反" aria-hidden="true">#</a> 取反</h3>
<p>我们使用<code v-pre>^</code>来进行取反</p>
<p>示例：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>    <span class="token keyword">var</span> str <span class="token operator">=</span> <span class="token string">'javascript'</span>
    <span class="token keyword">var</span> pattern <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">[^sj]</span><span class="token regex-delimiter">/</span></span>
    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>pattern<span class="token punctuation">.</span><span class="token function">exec</span><span class="token punctuation">(</span>str<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token comment">//["a", index: 1, input: "javascript", groups: undefined]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>如上， 匹配到了a， 不会去匹配s和j</p>
<h3 id="范围输入" tabindex="-1"><a class="header-anchor" href="#范围输入" aria-hidden="true">#</a> 范围输入</h3>
<p>我们使用<code v-pre>-</code>来连接输入的范围</p>
<p>示例：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>    <span class="token keyword">var</span> str <span class="token operator">=</span> <span class="token string">'javascript'</span>
    <span class="token keyword">var</span> pattern <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">[a-z]</span><span class="token regex-delimiter">/</span></span>
    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>pattern<span class="token punctuation">.</span><span class="token function">exec</span><span class="token punctuation">(</span>str<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token comment">//["j", index: 0, input: "javascript", groups: undefined]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>如上， a到z之间的字符全都能匹配到。如果也想匹配大写A-Z, 只需要这样写<code v-pre>/[a-zA-Z]/</code>。</p>
<p>匹配中文： <code v-pre>/[\u4e00-\u9fa5]/</code></p>
<h3 id="常用字符类" tabindex="-1"><a class="header-anchor" href="#常用字符类" aria-hidden="true">#</a> 常用字符类</h3>
<p>一般大写字符都是小写字符的取反。如<code v-pre>w</code>和<code v-pre>W</code>。</p>
<p><code v-pre>/./</code>  符号.可以匹配到换行符以外所有字符。 <code v-pre>/[^/n]/</code>的简写。
<code v-pre>w/</code>  字符w可以匹配a-zA-Z0-9_之间的字符。 <code v-pre>/[a-zA-Z0-9_]/</code>的简写。
<code v-pre>/W/</code>  大写字符W可以匹配a-zA-Z0-9_范围之外的字符。 <code v-pre>/[^a-zA-Z0-9_]/</code>的简写。
<code v-pre>/d/</code>  字符d可以匹配0-9之间的字符。<code v-pre>/[0-9]/</code>的简写。
<code v-pre>/\s/</code> \s用来匹配制表符和空格。</p>
<h3 id="重复" tabindex="-1"><a class="header-anchor" href="#重复" aria-hidden="true">#</a> 重复</h3>
<p>我们如果想匹配重复的字符可以这样写：</p>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>    var str = '110'
    var pattern = /\d{2}/
    console.log(pattern.exec(str));
    //["11", index: 0, input: "110", groups: undefined]
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>在匹配的字符后面添加{2}就可以匹配到2位符合条件的字符。</p>
<p>我们不仅可以写入要匹配字符的长度，
也可以写一个范围 如<code v-pre>{1,3}</code>。(一定不要在{1,3}之间添加空格)
匹配大于等于1的长度 <code v-pre>{1,}</code></p>
<h4 id="简写形式" tabindex="-1"><a class="header-anchor" href="#简写形式" aria-hidden="true">#</a> 简写形式：</h4>
<p><code v-pre>?</code> 表示0个至1个。 <code v-pre>/\d{0,1}/</code>
<code v-pre>+</code> 表示大于等于1。 <code v-pre>/\d{1,}/</code>
<code v-pre>*</code> 表示0次至多次  ``/\d{0,}/`</p>
<p>示例：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>   <span class="token keyword">var</span> str <span class="token operator">=</span> <span class="token string">'肯德基豪华午餐 ￥15.5！'</span>
    <span class="token keyword">var</span> pattern <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">\d+\.?\d*</span><span class="token regex-delimiter">/</span></span>
    console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>pattern<span class="token punctuation">.</span><span class="token function">exec</span><span class="token punctuation">(</span>str<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
    <span class="token comment">//["15.5", index: 9, input: "肯德基豪华午餐 ￥15.5！", groups: undefined]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="贪婪匹配" tabindex="-1"><a class="header-anchor" href="#贪婪匹配" aria-hidden="true">#</a> 贪婪匹配</h3>
<p>如果按照上面的重复匹配， 正则表达式就会尽可能多的去匹配字符，这个叫做贪婪匹配。</p>
<p>如果我们不想这样， 只想尽可能少的匹配(要符合条件)。这时我们一般使用<code v-pre>?</code>来写，表达非贪婪匹配。</p>
<p>如<code v-pre>\a??\</code>或<code v-pre>/a{0,1}?/</code>。</p>
<p>以下为简单地几个例子：</p>
<p>贪婪匹配</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>	<span class="token keyword">var</span> str <span class="token operator">=</span> <span class="token string">'aaab'</span><span class="token punctuation">;</span>
	<span class="token keyword">var</span> pattern <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">a+?b</span><span class="token regex-delimiter">/</span></span><span class="token punctuation">;</span>
	console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>pattern<span class="token punctuation">.</span><span class="token function">exec</span><span class="token punctuation">(</span>str<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
	<span class="token comment">//["aaab", index: 0, input: "aaab", groups: undefined]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>虽然这是一个非贪婪匹配， 但是它要符合条件的才可以， 只是尽可能的去少匹配。以上会匹配到aaab。</p>
<p>贪婪匹配：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>	<span class="token keyword">var</span> str <span class="token operator">=</span> <span class="token string">'&lt;td>&lt;p>a&lt;/p>&lt;/td>&lt;td>&lt;p>b&lt;/p>&lt;/td>'</span><span class="token punctuation">;</span>
	<span class="token keyword">var</span> pattern <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">&lt;td>.*&lt;\/td></span><span class="token regex-delimiter">/</span></span><span class="token punctuation">;</span>
	console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>pattern<span class="token punctuation">.</span><span class="token function">exec</span><span class="token punctuation">(</span>str<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
	<span class="token comment">//["&lt;td>&lt;p>a&lt;/p>&lt;/td>&lt;td>&lt;p>b&lt;/p>&lt;/td>", index: 0, input: "&lt;td>&lt;p>a&lt;/p>&lt;/td>&lt;td>&lt;p>b&lt;/p>&lt;/td>", groups: undefined]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>非贪婪匹配： 匹配第一个td标签之间字符</p>
<div class="language-text ext-text line-numbers-mode"><pre v-pre class="language-text"><code>	var str = '&lt;td>&lt;p>a&lt;/p>&lt;/td>&lt;td>&lt;p>b&lt;/p>&lt;/td>';
	var pattern = /&lt;td>.*?&lt;\/td>/;
	console.log(pattern.exec(str));
	
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>输出：</p>
<p><img src="https://blog-picgo-typora.oss-cn-hangzhou.aliyuncs.com/image-20220805091856678.png" alt="image-20220805091856678"></p>
<h2 id="选择、分组和引用" tabindex="-1"><a class="header-anchor" href="#选择、分组和引用" aria-hidden="true">#</a> 选择、分组和引用</h2>
<h3 id="选择" tabindex="-1"><a class="header-anchor" href="#选择" aria-hidden="true">#</a> 选择</h3>
<p>一般我们通过|来表示或， 只要匹配到一个就返回，后面的进行忽略。 如<code v-pre>/html|css|js/</code>。</p>
<h3 id="分组" tabindex="-1"><a class="header-anchor" href="#分组" aria-hidden="true">#</a> 分组</h3>
<p>一般我们通过<code v-pre>()</code>来进行分组</p>
<p>示例：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>	<span class="token keyword">var</span> str <span class="token operator">=</span> <span class="token string">'abab'</span><span class="token punctuation">;</span>
	<span class="token keyword">var</span> pattern <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">ab+</span><span class="token regex-delimiter">/</span></span><span class="token punctuation">;</span>
	console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>pattern<span class="token punctuation">.</span><span class="token function">exec</span><span class="token punctuation">(</span>str<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
	<span class="token comment">//["ab", index: 0, input: "abab", groups: undefined]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>以上只能匹配一个ab，因为<code v-pre>+</code>只对b起作用</p>
<p>如果想匹配ab多个可以加上括号</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>	<span class="token keyword">var</span> str <span class="token operator">=</span> <span class="token string">'abab'</span><span class="token punctuation">;</span>
	<span class="token keyword">var</span> pattern <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">(ab)+</span><span class="token regex-delimiter">/</span></span><span class="token punctuation">;</span>
	console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>pattern<span class="token punctuation">.</span><span class="token function">exec</span><span class="token punctuation">(</span>str<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>输出结果：</p>
<p><img src="https://blog-picgo-typora.oss-cn-hangzhou.aliyuncs.com/image-20220805091949273.png" alt=""></p>
<p>它返回的是一个数组，里面第一项是abab， 而第二项就是括号括起来的字符匹配（捕获性分组）</p>
<p>如果不想捕获， 可以加上?:</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>	<span class="token keyword">var</span> str <span class="token operator">=</span> <span class="token string">'abcd'</span><span class="token punctuation">;</span>
	<span class="token keyword">var</span> pattern <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">(?:ab)c</span><span class="token regex-delimiter">/</span></span><span class="token punctuation">;</span>
	console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>pattern<span class="token punctuation">.</span><span class="token function">exec</span><span class="token punctuation">(</span>str<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>多个括号匹配</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>	<span class="token keyword">var</span> str <span class="token operator">=</span> <span class="token string">'abcd'</span><span class="token punctuation">;</span>
	<span class="token keyword">var</span> pattern <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">(a(b(c)))</span><span class="token regex-delimiter">/</span></span><span class="token punctuation">;</span>
	console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>pattern<span class="token punctuation">.</span><span class="token function">exec</span><span class="token punctuation">(</span>str<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>括号从左到右进行匹配</p>
<p>匹配开始与结尾一致：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>	<span class="token keyword">var</span> str <span class="token operator">=</span> <span class="token string">'&lt;p>&lt;a>这是一段文字&lt;/a>&lt;/p>'</span><span class="token punctuation">;</span>
	<span class="token keyword">var</span> pattern <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">&lt;([a-zA-Z]+)>(.*?)&lt;\/\1></span><span class="token regex-delimiter">/</span></span><span class="token punctuation">;</span>
	console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>pattern<span class="token punctuation">.</span><span class="token function">exec</span><span class="token punctuation">(</span>str<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>输出结果：</p>
<p>\1标识第一个括号包括的内容， 使用\1可以保证与第一个括号里的内容完全一致。</p>
<h2 id="位置匹配" tabindex="-1"><a class="header-anchor" href="#位置匹配" aria-hidden="true">#</a> 位置匹配</h2>
<h3 id="首匹配" tabindex="-1"><a class="header-anchor" href="#首匹配" aria-hidden="true">#</a> 首匹配</h3>
<p>使用^可以做到首匹配</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>	<span class="token keyword">var</span> str <span class="token operator">=</span> <span class="token string">'html js'</span><span class="token punctuation">;</span>
	<span class="token keyword">var</span> str1<span class="token operator">=</span> <span class="token string">'js'</span><span class="token punctuation">;</span>
	<span class="token keyword">var</span> pattern <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">^js</span><span class="token regex-delimiter">/</span></span><span class="token punctuation">;</span>
	console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>pattern<span class="token punctuation">.</span><span class="token function">exec</span><span class="token punctuation">(</span>str<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span><span class="token comment">//null</span>
	console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>pattern<span class="token punctuation">.</span><span class="token function">exec</span><span class="token punctuation">(</span>str1<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span><span class="token comment">//["js", index: 0, input: "js", groups: undefined]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="尾匹配" tabindex="-1"><a class="header-anchor" href="#尾匹配" aria-hidden="true">#</a> 尾匹配</h3>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>	<span class="token keyword">var</span> str <span class="token operator">=</span> <span class="token string">'html js css'</span><span class="token punctuation">;</span>
	<span class="token keyword">var</span> str1 <span class="token operator">=</span> <span class="token string">'html js'</span><span class="token punctuation">;</span>
	<span class="token keyword">var</span> pattern <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">js$</span><span class="token regex-delimiter">/</span></span><span class="token punctuation">;</span>
	console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>pattern<span class="token punctuation">.</span><span class="token function">exec</span><span class="token punctuation">(</span>str<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span><span class="token comment">//null</span>
	console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>pattern<span class="token punctuation">.</span><span class="token function">exec</span><span class="token punctuation">(</span>str1<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span><span class="token comment">//["js", index: 5, input: "html js", groups: undefined]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>如何保证输入字符全是数字？</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>	<span class="token keyword">var</span> str <span class="token operator">=</span> <span class="token string">'110119120'</span><span class="token punctuation">;</span>
	<span class="token keyword">var</span> pattern <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">^\d+$</span><span class="token regex-delimiter">/</span></span><span class="token punctuation">;</span>
	console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>pattern<span class="token punctuation">.</span><span class="token function">exec</span><span class="token punctuation">(</span>str<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
	<span class="token keyword">if</span> <span class="token punctuation">(</span>pattern<span class="token punctuation">.</span><span class="token function">test</span><span class="token punctuation">(</span>str<span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
		console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">'全是数字！'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
	<span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span>
		console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">'不全是数字！'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
	<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>也可以这么写：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>	<span class="token keyword">var</span> str <span class="token operator">=</span> <span class="token string">'11011a9120'</span><span class="token punctuation">;</span>
	<span class="token keyword">var</span> pattern <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">\D</span><span class="token regex-delimiter">/</span></span><span class="token punctuation">;</span>
	console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>pattern<span class="token punctuation">.</span><span class="token function">exec</span><span class="token punctuation">(</span>str<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
	<span class="token keyword">if</span> <span class="token punctuation">(</span>pattern<span class="token punctuation">.</span><span class="token function">test</span><span class="token punctuation">(</span>str<span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
		console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">'不全是数字！'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
	<span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span>
		console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">'全是数字！'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
	<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="单词边界匹配" tabindex="-1"><a class="header-anchor" href="#单词边界匹配" aria-hidden="true">#</a> 单词边界匹配</h3>
<p>\b匹配单词边界，表示的就是\w和\W之间的位置。
应用场景：当元素有多个类名时，匹配其中的一个类名（有三种位置：行首、行尾、中间)。
在构造函数参数中的转义字符都要进行双重转义。 如果正则里面为空可以匹配任何字符串。</p>
<p>示例：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>	<span class="token keyword">var</span> str <span class="token operator">=</span> <span class="token string">'js html'</span><span class="token punctuation">;</span>
	<span class="token keyword">var</span> str1 <span class="token operator">=</span><span class="token string">'js'</span><span class="token punctuation">;</span>
	<span class="token keyword">var</span> pattern <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">js\b</span><span class="token regex-delimiter">/</span></span><span class="token punctuation">;</span>
	console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>pattern<span class="token punctuation">.</span><span class="token function">exec</span><span class="token punctuation">(</span>str<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span><span class="token comment">//["js", index: 0, input: "js html", groups: undefined]</span>
	console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>pattern<span class="token punctuation">.</span><span class="token function">exec</span><span class="token punctuation">(</span>str1<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span><span class="token comment">//["js", index: 0, input: "js", groups: undefined]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>	<span class="token keyword">var</span> str <span class="token operator">=</span> <span class="token string">'@@@js@@@'</span><span class="token punctuation">;</span>
	<span class="token keyword">var</span> pattern <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">\bjs\b</span><span class="token regex-delimiter">/</span></span><span class="token punctuation">;</span>
	console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>pattern<span class="token punctuation">.</span><span class="token function">exec</span><span class="token punctuation">(</span>str<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
	<span class="token comment">//["js", index: 3, input: "@@@js@@@", groups: undefined]</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>匹配到了两个@之间js的位置</p>
<p>匹配一个class类名</p>
<div class="language-html ext-html line-numbers-mode"><pre v-pre class="language-html"><code><span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>p</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>odd2      odd    <span class="token punctuation">"</span></span><span class="token punctuation">></span></span>1<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>p</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>p</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>even<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>2<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>p</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>p</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>odd<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>3<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>p</span><span class="token punctuation">></span></span>
<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;</span>p</span> <span class="token attr-name">class</span><span class="token attr-value"><span class="token punctuation attr-equals">=</span><span class="token punctuation">"</span>even<span class="token punctuation">"</span></span><span class="token punctuation">></span></span>4<span class="token tag"><span class="token tag"><span class="token punctuation">&lt;/</span>p</span><span class="token punctuation">></span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>	<span class="token keyword">var</span> oddP <span class="token operator">=</span> <span class="token function">getByClassName</span><span class="token punctuation">(</span><span class="token string">'odd'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
	<span class="token keyword">var</span> evenP <span class="token operator">=</span> <span class="token function">getByClassName</span><span class="token punctuation">(</span><span class="token string">'even'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
	<span class="token keyword">for</span> <span class="token punctuation">(</span><span class="token keyword">var</span> i <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span> i <span class="token operator">&lt;</span> oddP<span class="token punctuation">.</span>length<span class="token punctuation">;</span> i<span class="token operator">++</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
		oddP<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">.</span>style<span class="token punctuation">.</span>backgroundColor <span class="token operator">=</span> <span class="token string">'red'</span><span class="token punctuation">;</span>
	<span class="token punctuation">}</span>
	<span class="token keyword">for</span> <span class="token punctuation">(</span><span class="token keyword">var</span> i <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span> i <span class="token operator">&lt;</span> evenP<span class="token punctuation">.</span>length<span class="token punctuation">;</span> i<span class="token operator">++</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
		evenP<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">.</span>style<span class="token punctuation">.</span>backgroundColor <span class="token operator">=</span> <span class="token string">'yellow'</span><span class="token punctuation">;</span>
	<span class="token punctuation">}</span>

	<span class="token keyword">function</span> <span class="token function">getByClassName</span><span class="token punctuation">(</span><span class="token parameter">className<span class="token punctuation">,</span> parentNode</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
		<span class="token keyword">if</span> <span class="token punctuation">(</span>document<span class="token punctuation">.</span>getElementsByClassName<span class="token punctuation">)</span> <span class="token punctuation">{</span>
			<span class="token keyword">return</span> document<span class="token punctuation">.</span><span class="token function">getElementsByClassName</span><span class="token punctuation">(</span>className<span class="token punctuation">)</span><span class="token punctuation">;</span>
		<span class="token punctuation">}</span> <span class="token keyword">else</span> <span class="token punctuation">{</span>console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token number">1</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
			parentNode <span class="token operator">=</span> parentNode <span class="token operator">||</span> document<span class="token punctuation">;</span>
			<span class="token keyword">var</span> nodeList <span class="token operator">=</span> <span class="token punctuation">[</span><span class="token punctuation">]</span><span class="token punctuation">;</span>
			<span class="token keyword">var</span> allNodes <span class="token operator">=</span> parentNode<span class="token punctuation">.</span><span class="token function">getElementsByTagName</span><span class="token punctuation">(</span><span class="token string">'*'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
			<span class="token keyword">var</span> pattern <span class="token operator">=</span> <span class="token keyword">new</span> <span class="token class-name">RegExp</span><span class="token punctuation">(</span><span class="token string">'\\b'</span> <span class="token operator">+</span> className <span class="token operator">+</span> <span class="token string">'\\b'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

			<span class="token keyword">for</span> <span class="token punctuation">(</span><span class="token keyword">var</span> i <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span> i <span class="token operator">&lt;</span> allNodes<span class="token punctuation">.</span>length<span class="token punctuation">;</span> i<span class="token operator">++</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
				<span class="token keyword">if</span> <span class="token punctuation">(</span>pattern<span class="token punctuation">.</span><span class="token function">test</span><span class="token punctuation">(</span>allNodes<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">.</span>className<span class="token punctuation">)</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
					nodeList<span class="token punctuation">.</span><span class="token function">push</span><span class="token punctuation">(</span>allNodes<span class="token punctuation">[</span>i<span class="token punctuation">]</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
				<span class="token punctuation">}</span>
			<span class="token punctuation">}</span>

			<span class="token keyword">return</span> nodeList<span class="token punctuation">;</span>
		<span class="token punctuation">}</span>
	<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>使用了<code v-pre>new RegExp('\\b' + className + '\\b')</code>， 构造函数的s需要双重转义， 需要加两个\斜杠。</p>
<p>此次匹配不仅能匹配到以odd开始， 也可以匹配到odd在中间， 或者在末尾。只要odd是一个单独的单词即可。</p>
<p>输出结果：</p>
<p><img src="https://blog-picgo-typora.oss-cn-hangzhou.aliyuncs.com/image-20220805092321719.png" alt="image-20220805092321719"></p>
<h3 id="前瞻性匹配" tabindex="-1"><a class="header-anchor" href="#前瞻性匹配" aria-hidden="true">#</a> 前瞻性匹配</h3>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>	<span class="token keyword">var</span> str <span class="token operator">=</span> <span class="token string">'java'</span><span class="token punctuation">;</span>
	<span class="token keyword">var</span> str1 <span class="token operator">=</span> <span class="token string">'javascript'</span>
	<span class="token keyword">var</span> pattern <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">java(?=script)</span><span class="token regex-delimiter">/</span></span><span class="token punctuation">;</span>
	console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>pattern<span class="token punctuation">.</span><span class="token function">exec</span><span class="token punctuation">(</span>str<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
	console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>pattern<span class="token punctuation">.</span><span class="token function">exec</span><span class="token punctuation">(</span>str1<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>只有java后面跟的是script才可以匹配到，用?=来进行匹配</p>
<p><img src="https://blog-picgo-typora.oss-cn-hangzhou.aliyuncs.com/image-20220805092338872.png" alt="image-20220805092338872"></p>
<h3 id="负向前瞻性匹配" tabindex="-1"><a class="header-anchor" href="#负向前瞻性匹配" aria-hidden="true">#</a> 负向前瞻性匹配</h3>
<p>与前瞻性匹配相反的是负向前瞻性匹配</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>	<span class="token keyword">var</span> str <span class="token operator">=</span> <span class="token string">'java'</span><span class="token punctuation">;</span>
	<span class="token keyword">var</span> str1 <span class="token operator">=</span> <span class="token string">'javascript'</span>
	<span class="token keyword">var</span> pattern <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">java(?!script)</span><span class="token regex-delimiter">/</span></span><span class="token punctuation">;</span>
	console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>pattern<span class="token punctuation">.</span><span class="token function">exec</span><span class="token punctuation">(</span>str<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
	console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>pattern<span class="token punctuation">.</span><span class="token function">exec</span><span class="token punctuation">(</span>str1<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>它用?!来进行匹配，表示后面跟的不是script才可以匹配到。</p>
<p><img src="https://blog-picgo-typora.oss-cn-hangzhou.aliyuncs.com/image-20220805092354679.png" alt="image-20220805092354679"></p>
<h2 id="regexp对象的实例方法" tabindex="-1"><a class="header-anchor" href="#regexp对象的实例方法" aria-hidden="true">#</a> RegExp对象的实例方法</h2>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>	console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token keyword">new</span> <span class="token class-name">RegExp</span><span class="token punctuation">(</span><span class="token string">'\\b'</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
	<span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">\\</span><span class="token regex-delimiter">/</span></span>
	<span class="token keyword">new</span> <span class="token class-name">RegExp</span><span class="token punctuation">(</span><span class="token string">'\\\\'</span><span class="token punctuation">)</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>要谨记， 构造函数的正则需要双重转义， 如果构造函数想要匹配一个<code v-pre>\</code>， 需要使用4个<code v-pre>\</code>来进行匹配。</p>
<h3 id="实例方法" tabindex="-1"><a class="header-anchor" href="#实例方法" aria-hidden="true">#</a> 实例方法</h3>
<p>test(),exec()都是正则的实例方法。</p>
<p>一般来说exec只匹配到第一个匹配的字符。 如果想继续向下匹配可以增加<code v-pre>g</code>修饰符。</p>
<p>如果匹配到末尾继续进行匹配， 会重新匹配会第一个。</p>
<h3 id="正则相关方法" tabindex="-1"><a class="header-anchor" href="#正则相关方法" aria-hidden="true">#</a> 正则相关方法</h3>
<h4 id="search-正则表达式" tabindex="-1"><a class="header-anchor" href="#search-正则表达式" aria-hidden="true">#</a> search(正则表达式);</h4>
<p>//判断是否存在该正则匹配的字符串，有一个则返回匹配到的位置的索引。
找不到返回-1；有多个，依然返回第一个索引，与g全局匹配无关紧要。参数可以为字符串，但该字符串最终还是会转化为正则来判断。</p>
<p>示例：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>	<span class="token keyword">var</span> str <span class="token operator">=</span> <span class="token string">'html js js'</span><span class="token punctuation">;</span>
	<span class="token keyword">var</span> pattern <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">js</span><span class="token regex-delimiter">/</span></span><span class="token punctuation">;</span>
	console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>str<span class="token punctuation">.</span><span class="token function">search</span><span class="token punctuation">(</span>pattern<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span><span class="token comment">//5</span>

	<span class="token keyword">var</span> str <span class="token operator">=</span> <span class="token string">'html js js'</span><span class="token punctuation">;</span>
	console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>str<span class="token punctuation">.</span><span class="token function">search</span><span class="token punctuation">(</span><span class="token string">'js'</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span><span class="token comment">//5</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h4 id="match-正则表达式" tabindex="-1"><a class="header-anchor" href="#match-正则表达式" aria-hidden="true">#</a> match(正则表达式);</h4>
<p>//返回一个匹配的数组，和exec()方法类似；不同的地方仅在于：全局匹配时，该方法会一次性返回所有匹配的字符串在一个数组中，并且不会返回分组匹配到的字符串。</p>
<p>match：非全局的情况下才会返回分组中匹配到的内容，全局匹配只能匹配到所有匹配到的字符（不返回分组匹配到的字符）。</p>
<p>exec：无论是否全局匹配都会返回分组中匹配到的内容，并且都只会返回当前匹配到的一个内容，而不是全部返回。</p>
<p>示例：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>	<span class="token keyword">var</span> str <span class="token operator">=</span> <span class="token string">'js js js'</span><span class="token punctuation">;</span>
	<span class="token keyword">var</span> pattern <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">(j)s</span><span class="token regex-delimiter">/</span><span class="token regex-flags">g</span></span><span class="token punctuation">;</span>
	console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>str<span class="token punctuation">.</span><span class="token function">match</span><span class="token punctuation">(</span>pattern<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
	console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>pattern<span class="token punctuation">.</span><span class="token function">exec</span><span class="token punctuation">(</span>str<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p><img src="https://blog-picgo-typora.oss-cn-hangzhou.aliyuncs.com/image-20220805092412429.png" alt="image-20220805092412429"></p>
<p>有换行的地方才会用到m多行匹配。一般会和g连用。默认情况下是都有多行匹配的。一般与
$或^ 存在的时候才会发挥作用。</p>
<h4 id="split" tabindex="-1"><a class="header-anchor" href="#split" aria-hidden="true">#</a> split();</h4>
<p>//该字符串方法是将参数所表示的字符作为分割成多个数组元素的标志，该字符串方法传入正则表达式也可使用。</p>
<p>示例：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>	<span class="token keyword">var</span> str <span class="token operator">=</span> <span class="token string">'html ,   css  ,   js'</span><span class="token punctuation">;</span>
	<span class="token keyword">var</span> pattern <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">\s*,\s*</span><span class="token regex-delimiter">/</span></span><span class="token punctuation">;</span>
	console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>str<span class="token punctuation">.</span><span class="token function">split</span><span class="token punctuation">(</span>pattern<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>输出结果：</p>
<p><img src="https://blog-picgo-typora.oss-cn-hangzhou.aliyuncs.com/image-20220805092428542.png" alt="image-20220805092428542"></p>
<h4 id="replace方法" tabindex="-1"><a class="header-anchor" href="#replace方法" aria-hidden="true">#</a> replace方法</h4>
<p>字符串的replace()方法：返回的是新的字符串。</p>
<ul>
<li>第一个参数，字符串里要被替换的字符。</li>
<li>第二个参数，替换的字符。</li>
</ul>
<p>只能替换一个。传入正则作为参数，利用正则的全局匹配可以替换多个。</p>
<p>string的replace方法也能引用正则的分组，第二个参数传入‘$1’，表示为正则的第一个分组。replace方法返回的是一个新的字符串。</p>
<h5 id="应用场景" tabindex="-1"><a class="header-anchor" href="#应用场景" aria-hidden="true">#</a> 应用场景：</h5>
<p>可以用来过滤敏感词，将敏感词用*代替。
string的replace方法的第二个参数可以是函数function，传入$0，$0表示母匹配(正则最大的匹
配)，$1表示分组中的子匹配。然后用函数的返回值去替换正则($0)。</p>
<p>示例：</p>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>	<span class="token keyword">var</span> str <span class="token operator">=</span> <span class="token string">'中国军队和阿扁一起办证'</span><span class="token punctuation">;</span>
	<span class="token keyword">var</span> pattern <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">国军|阿扁|办证</span><span class="token regex-delimiter">/</span><span class="token regex-flags">g</span></span><span class="token punctuation">;</span>
	console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>str<span class="token punctuation">.</span><span class="token function">replace</span><span class="token punctuation">(</span>pattern<span class="token punctuation">,</span> <span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token parameter">$0</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
		console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>$0<span class="token punctuation">)</span><span class="token punctuation">;</span>
		<span class="token keyword">var</span> result <span class="token operator">=</span> <span class="token string">''</span><span class="token punctuation">;</span>
		<span class="token keyword">for</span> <span class="token punctuation">(</span><span class="token keyword">var</span> i <span class="token operator">=</span> <span class="token number">0</span><span class="token punctuation">;</span> i <span class="token operator">&lt;</span> $0<span class="token punctuation">.</span>length<span class="token punctuation">;</span> i<span class="token operator">++</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
			result <span class="token operator">+=</span> <span class="token string">'*'</span><span class="token punctuation">;</span>
		<span class="token punctuation">}</span>

		<span class="token keyword">return</span> result<span class="token punctuation">;</span>
	<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><p>输出结果：</p>
<p><img src="https://blog-picgo-typora.oss-cn-hangzhou.aliyuncs.com/image-20220805092450795.png" alt="image-20220805092450795"></p>
<h2 id="常用正则表达式" tabindex="-1"><a class="header-anchor" href="#常用正则表达式" aria-hidden="true">#</a> 常用正则表达式</h2>
<h3 id="qq号" tabindex="-1"><a class="header-anchor" href="#qq号" aria-hidden="true">#</a> QQ号</h3>
<p>条件：</p>
<ul>
<li>全是数字</li>
<li>首位不能为0</li>
<li>最少5位(10000)</li>
<li>目前最多11位？</li>
</ul>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">^[1-9]\d{4,10}$</span><span class="token regex-delimiter">/</span></span>
<span class="token operator">/</span><span class="token operator">^</span><span class="token punctuation">[</span><span class="token number">1</span><span class="token operator">-</span><span class="token number">9</span><span class="token punctuation">]</span>\d<span class="token punctuation">{</span><span class="token number">4</span><span class="token punctuation">,</span><span class="token punctuation">}</span>$<span class="token operator">/</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="昵称" tabindex="-1"><a class="header-anchor" href="#昵称" aria-hidden="true">#</a> 昵称</h3>
<p>条件：</p>
<ul>
<li>中、英文、数字以及下划线</li>
<li>2-18位</li>
</ul>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>	<span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">^[\u4e00-\u9fa5a-zA-Z0-9_]{2,18}$</span><span class="token regex-delimiter">/</span></span>
	<span class="token operator">/</span><span class="token operator">^</span><span class="token punctuation">[</span>\u4e00<span class="token operator">-</span>\u9fa5\w<span class="token punctuation">]</span><span class="token punctuation">{</span><span class="token number">2</span><span class="token punctuation">,</span><span class="token number">18</span><span class="token punctuation">}</span>$<span class="token operator">/</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="密码" tabindex="-1"><a class="header-anchor" href="#密码" aria-hidden="true">#</a> 密码</h3>
<p>条件：</p>
<ul>
<li>6-16位</li>
<li>不能用空白字符\s</li>
</ul>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>	<span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">^\S{6,16}$</span><span class="token regex-delimiter">/</span></span>
	<span class="token operator">/</span><span class="token operator">^</span><span class="token punctuation">[</span>\w<span class="token operator">~</span><span class="token operator">!</span>@#$<span class="token operator">%</span><span class="token operator">^</span>\<span class="token punctuation">[</span>\<span class="token punctuation">]</span><span class="token punctuation">]</span><span class="token punctuation">{</span><span class="token number">6</span><span class="token punctuation">,</span><span class="token number">16</span><span class="token punctuation">}</span>$<span class="token operator">/</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="去除字符串首尾的空白字符" tabindex="-1"><a class="header-anchor" href="#去除字符串首尾的空白字符" aria-hidden="true">#</a> 去除字符串首尾的空白字符</h3>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>	<span class="token keyword">var</span> str <span class="token operator">=</span> <span class="token string">'        Alex         '</span><span class="token punctuation">;</span>
	<span class="token keyword">var</span> pattern <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">^\s+</span><span class="token regex-delimiter">/</span></span><span class="token punctuation">;</span>
	console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">'|'</span> <span class="token operator">+</span> str<span class="token punctuation">.</span><span class="token function">replace</span><span class="token punctuation">(</span>pattern<span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">)</span> <span class="token operator">+</span> <span class="token string">'|'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

	<span class="token keyword">var</span> str <span class="token operator">=</span> <span class="token string">'        Alex         '</span><span class="token punctuation">;</span>
	<span class="token keyword">var</span> pattern <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">\s+$</span><span class="token regex-delimiter">/</span></span><span class="token punctuation">;</span>
	console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">'|'</span> <span class="token operator">+</span> str<span class="token punctuation">.</span><span class="token function">replace</span><span class="token punctuation">(</span>pattern<span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">)</span> <span class="token operator">+</span> <span class="token string">'|'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

	<span class="token keyword">var</span> str <span class="token operator">=</span> <span class="token string">'        Alex         '</span><span class="token punctuation">;</span>
	<span class="token keyword">var</span> pattern <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">^\s+|\s+$</span><span class="token regex-delimiter">/</span><span class="token regex-flags">g</span></span><span class="token punctuation">;</span>
	console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">'|'</span> <span class="token operator">+</span> str<span class="token punctuation">.</span><span class="token function">replace</span><span class="token punctuation">(</span>pattern<span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">)</span> <span class="token operator">+</span> <span class="token string">'|'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

	<span class="token keyword">var</span> str <span class="token operator">=</span> <span class="token string">'        Alex         '</span><span class="token punctuation">;</span>
	<span class="token keyword">var</span> pattern1 <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">^\s+</span><span class="token regex-delimiter">/</span></span><span class="token punctuation">;</span>
	<span class="token keyword">var</span> pattern2 <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">\s+$</span><span class="token regex-delimiter">/</span></span><span class="token punctuation">;</span>
	console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">'|'</span> <span class="token operator">+</span> str<span class="token punctuation">.</span><span class="token function">replace</span><span class="token punctuation">(</span>pattern1<span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">replace</span><span class="token punctuation">(</span>pattern2<span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">)</span> <span class="token operator">+</span> <span class="token string">'|'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

	<span class="token keyword">function</span> <span class="token function">trim</span><span class="token punctuation">(</span><span class="token parameter">str</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
		<span class="token keyword">return</span> str<span class="token punctuation">.</span><span class="token function">replace</span><span class="token punctuation">(</span><span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">^\s+</span><span class="token regex-delimiter">/</span></span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">)</span><span class="token punctuation">.</span><span class="token function">replace</span><span class="token punctuation">(</span><span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">\s+$</span><span class="token regex-delimiter">/</span></span><span class="token punctuation">,</span> <span class="token string">''</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
	<span class="token punctuation">}</span>
	<span class="token comment">// trimLeft trimRight</span>
	<span class="token keyword">var</span> str <span class="token operator">=</span> <span class="token string">'        Alex         '</span><span class="token punctuation">;</span>
	console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span><span class="token string">'|'</span> <span class="token operator">+</span> <span class="token function">trim</span><span class="token punctuation">(</span>str<span class="token punctuation">)</span> <span class="token operator">+</span> <span class="token string">'|'</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="转驼峰" tabindex="-1"><a class="header-anchor" href="#转驼峰" aria-hidden="true">#</a> 转驼峰</h3>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>	<span class="token comment">// css: background-color: red;</span>
	<span class="token comment">// js: elem.style.backgroundColor = 'red';</span>
	<span class="token comment">// jquery: $(elem).css('background-color', 'red');</span>

	<span class="token keyword">var</span> str <span class="token operator">=</span> <span class="token string">'background-color'</span><span class="token punctuation">;</span>
	<span class="token keyword">var</span> pattern <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">-([a-z])</span><span class="token regex-delimiter">/</span><span class="token regex-flags">gi</span></span><span class="token punctuation">;</span>
	console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>str<span class="token punctuation">.</span><span class="token function">replace</span><span class="token punctuation">(</span>pattern<span class="token punctuation">,</span> <span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token parameter">all<span class="token punctuation">,</span> letter</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
		<span class="token keyword">return</span> letter<span class="token punctuation">.</span><span class="token function">toUpperCase</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
	<span class="token punctuation">}</span><span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

	<span class="token keyword">function</span> <span class="token function">toCamelCase</span><span class="token punctuation">(</span><span class="token parameter">str</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
		<span class="token keyword">return</span> str<span class="token punctuation">.</span><span class="token function">replace</span><span class="token punctuation">(</span>pattern<span class="token punctuation">,</span> <span class="token keyword">function</span> <span class="token punctuation">(</span><span class="token parameter">all<span class="token punctuation">,</span> letter</span><span class="token punctuation">)</span> <span class="token punctuation">{</span>
			<span class="token keyword">return</span> letter<span class="token punctuation">.</span><span class="token function">toUpperCase</span><span class="token punctuation">(</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
		<span class="token punctuation">}</span><span class="token punctuation">)</span>
	<span class="token punctuation">}</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="匹配html标签" tabindex="-1"><a class="header-anchor" href="#匹配html标签" aria-hidden="true">#</a> 匹配HTML标签</h3>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>	<span class="token keyword">var</span> str <span class="token operator">=</span> <span class="token string">'&lt;p class="odd" id="odd">123&lt;/p>'</span><span class="token punctuation">;</span>
	<span class="token keyword">var</span> pattern <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">&lt;\/?[a-zA-Z]+(\s+[a-zA-Z]+=".*")*></span><span class="token regex-delimiter">/</span><span class="token regex-flags">g</span></span><span class="token punctuation">;</span>
	console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>str<span class="token punctuation">.</span><span class="token function">match</span><span class="token punctuation">(</span>pattern<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

	<span class="token keyword">var</span> str <span class="token operator">=</span> <span class="token string">'&lt;p class="odd" id="odd">123&lt;/p>'</span><span class="token punctuation">;</span>
	<span class="token keyword">var</span> pattern <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">&lt;[^>]+></span><span class="token regex-delimiter">/</span><span class="token regex-flags">g</span></span><span class="token punctuation">;</span>
	console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>str<span class="token punctuation">.</span><span class="token function">match</span><span class="token punctuation">(</span>pattern<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

	<span class="token keyword">var</span> str <span class="token operator">=</span> <span class="token string">'&lt;input type="text" value=">" name="username" />'</span><span class="token punctuation">;</span>
	<span class="token keyword">var</span> pattern <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">&lt;(?:[^"'>]|"[^"]*"|'[^']*')*></span><span class="token regex-delimiter">/</span><span class="token regex-flags">g</span></span><span class="token punctuation">;</span>
	console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>str<span class="token punctuation">.</span><span class="token function">match</span><span class="token punctuation">(</span>pattern<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>

	<span class="token keyword">var</span> str <span class="token operator">=</span> <span class="token string">'&lt;input type="text" value=">" name="username" />'</span><span class="token punctuation">;</span>
	<span class="token keyword">var</span> pattern <span class="token operator">=</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">&lt;(?:[^"'>]|(["'])[^"']*\1)*></span><span class="token regex-delimiter">/</span><span class="token regex-flags">g</span></span><span class="token punctuation">;</span>
	console<span class="token punctuation">.</span><span class="token function">log</span><span class="token punctuation">(</span>str<span class="token punctuation">.</span><span class="token function">match</span><span class="token punctuation">(</span>pattern<span class="token punctuation">)</span><span class="token punctuation">)</span><span class="token punctuation">;</span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="匹配邮箱" tabindex="-1"><a class="header-anchor" href="#匹配邮箱" aria-hidden="true">#</a> 匹配邮箱</h3>
<p>条件：</p>
<ul>
<li>alex@yahoo.com.cn</li>
<li>alex_1@yahoo.com.cn</li>
<li>alex_1.a-sdasd.asdasdas.com@yah-o_o.com.adasdsd.cn</li>
</ul>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">(?:\w+\.)*\w+@(?:\w+\.)+[a-z]</span><span class="token regex-delimiter">/</span><span class="token regex-flags">i</span></span>
<span class="token operator">/</span><span class="token operator">^</span><span class="token punctuation">[</span>a<span class="token operator">-</span>z0<span class="token operator">-</span><span class="token number">9</span><span class="token punctuation">]</span><span class="token operator">+</span><span class="token punctuation">(</span><span class="token operator">?</span><span class="token operator">:</span><span class="token punctuation">[</span><span class="token punctuation">.</span>_<span class="token operator">-</span><span class="token punctuation">]</span><span class="token punctuation">[</span>a<span class="token operator">-</span>z0<span class="token operator">-</span><span class="token number">9</span><span class="token punctuation">]</span><span class="token operator">+</span><span class="token punctuation">)</span><span class="token operator">*</span>@<span class="token punctuation">[</span>a<span class="token operator">-</span>z0<span class="token operator">-</span><span class="token number">9</span><span class="token punctuation">]</span><span class="token operator">+</span><span class="token punctuation">(</span><span class="token operator">?</span><span class="token operator">:</span><span class="token punctuation">[</span><span class="token punctuation">.</span>_<span class="token operator">-</span><span class="token punctuation">]</span><span class="token punctuation">[</span>a<span class="token operator">-</span>z0<span class="token operator">-</span><span class="token number">9</span><span class="token punctuation">]</span><span class="token operator">+</span><span class="token punctuation">)</span><span class="token operator">*</span>\<span class="token punctuation">.</span><span class="token punctuation">[</span>a<span class="token operator">-</span>z<span class="token punctuation">]</span><span class="token punctuation">{</span><span class="token number">2</span><span class="token punctuation">,</span><span class="token number">4</span><span class="token punctuation">}</span>$<span class="token operator">/</span>i
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div></div></div><h3 id="url" tabindex="-1"><a class="header-anchor" href="#url" aria-hidden="true">#</a> URL</h3>
<p>条件：</p>
<ul>
<li>(协议://)主机名(:端口号)(/路径)</li>
<li>ftp|http|https|mailto|file:///</li>
</ul>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code><span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">^(https?:\/\/)?([^:\/]+)(:\d+)?(\/.*)?$</span><span class="token regex-delimiter">/</span></span>
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div></div></div><h3 id="匹配主机名" tabindex="-1"><a class="header-anchor" href="#匹配主机名" aria-hidden="true">#</a> 匹配主机名</h3>
<div class="language-javascript ext-js line-numbers-mode"><pre v-pre class="language-javascript"><code>	<span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">[^:\/]+</span><span class="token regex-delimiter">/</span></span>
	<span class="token comment">//-www.-imos-oc.casfasf.sadasd.co-m</span>
	<span class="token comment">//ai</span>
	<span class="token operator">/</span><span class="token punctuation">[</span>a<span class="token operator">-</span>z0<span class="token operator">-</span><span class="token number">9</span><span class="token punctuation">]</span><span class="token operator">|</span><span class="token punctuation">[</span>a<span class="token operator">-</span>z0<span class="token operator">-</span><span class="token number">9</span><span class="token punctuation">]</span><span class="token punctuation">[</span><span class="token operator">-</span>a<span class="token operator">-</span>z0<span class="token operator">-</span><span class="token number">9</span><span class="token punctuation">]</span><span class="token operator">*</span><span class="token punctuation">[</span>a<span class="token operator">-</span>z0<span class="token operator">-</span><span class="token number">9</span><span class="token punctuation">]</span><span class="token operator">/</span>i
	<span class="token operator">/</span><span class="token operator">^</span><span class="token punctuation">(</span><span class="token punctuation">[</span>a<span class="token operator">-</span>z0<span class="token operator">-</span><span class="token number">9</span><span class="token punctuation">]</span>\<span class="token punctuation">.</span><span class="token operator">|</span><span class="token punctuation">[</span>a<span class="token operator">-</span>z0<span class="token operator">-</span><span class="token number">9</span><span class="token punctuation">]</span><span class="token punctuation">[</span><span class="token operator">-</span>a<span class="token operator">-</span>z0<span class="token operator">-</span><span class="token number">9</span><span class="token punctuation">]</span><span class="token operator">*</span><span class="token punctuation">[</span>a<span class="token operator">-</span>z0<span class="token operator">-</span><span class="token number">9</span><span class="token punctuation">]</span>\<span class="token punctuation">.</span><span class="token punctuation">)</span><span class="token operator">*</span><span class="token punctuation">(</span>com<span class="token operator">|</span>edu<span class="token operator">|</span>gov<span class="token operator">|</span>net<span class="token operator">|</span>org<span class="token operator">|</span><span class="token punctuation">[</span>a<span class="token operator">-</span>z<span class="token punctuation">]</span><span class="token punctuation">{</span><span class="token number">2</span><span class="token punctuation">}</span><span class="token punctuation">)</span>$<span class="token operator">/</span>i
	<span class="token operator">/</span><span class="token operator">^</span><span class="token punctuation">(</span><span class="token punctuation">[</span>a<span class="token operator">-</span>z0<span class="token operator">-</span><span class="token number">9</span><span class="token punctuation">]</span>\<span class="token punctuation">.</span><span class="token operator">|</span><span class="token punctuation">[</span>a<span class="token operator">-</span>z0<span class="token operator">-</span><span class="token number">9</span><span class="token punctuation">]</span><span class="token punctuation">[</span><span class="token operator">-</span>a<span class="token operator">-</span>z0<span class="token operator">-</span><span class="token number">9</span><span class="token punctuation">]</span><span class="token operator">*</span><span class="token punctuation">[</span>a<span class="token operator">-</span>z0<span class="token operator">-</span><span class="token number">9</span><span class="token punctuation">]</span>\<span class="token punctuation">.</span><span class="token punctuation">)</span><span class="token operator">*</span><span class="token punctuation">(</span><span class="token punctuation">[</span>a<span class="token operator">-</span>z<span class="token punctuation">]</span><span class="token operator">+</span><span class="token punctuation">)</span>$<span class="token operator">/</span>i

	<span class="token keyword">var</span> regexp <span class="token operator">=</span> <span class="token punctuation">{</span>
		<span class="token string-property property">'chinese'</span><span class="token operator">:</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">[\u4e00-\u9fa5]</span><span class="token regex-delimiter">/</span></span><span class="token punctuation">,</span> <span class="token comment">// </span>
		<span class="token string-property property">'qq'</span><span class="token operator">:</span> <span class="token regex"><span class="token regex-delimiter">/</span><span class="token regex-source language-regex">^[1-9]\d{4,}$</span><span class="token regex-delimiter">/</span></span><span class="token punctuation">,</span>
		<span class="token operator">...</span><span class="token punctuation">.</span>
	<span class="token punctuation">}</span><span class="token punctuation">;</span>
	regexp<span class="token punctuation">.</span>qq
</code></pre><div class="line-numbers" aria-hidden="true"><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div><div class="line-number"></div></div></div></div></template>


